# Combining Counts
# Code to combine different count matricies generated by different alignment runs

# Import libraries 
library(tidyverse)

# Read counts into variables
# Iyer Lab Counts
rawcountsIyer <-  read.table("../Scaled_Inputs/ZL_salmon.merged.gene_counts_length_scaled.tsv", 
                          sep="\t", header=TRUE, check.names=FALSE)
# Primary Sensory
rawcountsPrimaryDRG <- read.table("../Scaled_Inputs/NguyenDRG_salmon.merged.gene_counts_length_scaled.tsv",
                                  sep="\t", header=TRUE, check.names=FALSE)
# Primary Sympathetic
rawcountsPrimarySG <- read.table("../Scaled_Inputs/HabermanSG_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
# Primary Schwann Cells
rawcountsPrimarySchwanns <- read.table("../Scaled_Inputs/MajdPrimary_salmon.merged.gene_counts_length_scaled.tsv",
                                       sep="\t", header=TRUE, check.names=FALSE)
# Other Neural Crest
rawcountsFattahiTNC <- read.table("../Scaled_Inputs/FattahiNCs_salmon.merged.gene_counts_length_scaled.tsv",
                                       sep="\t", header=TRUE, check.names=FALSE)
# Other Sympathetic
rawcountsWuSymp <- read.table("../Scaled_Inputs/WuSymNs_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
rawcountsLiuSGO <- read.table("../Scaled_Inputs/LiuSympO_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
# Other Sensory
rawcountsDeng28Sens <- read.table("../Scaled_Inputs/DengSNs_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
rawcountsDeng56Sens <- read.table("../Scaled_Inputs/DengD56SNs_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
rawcountsCantorSens <- read.table("../Scaled_Inputs/CantorSNs_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
rawcountsMalkaSens <- read.table("../Scaled_Inputs/Malka-gSNs_salmon.merged.gene_counts_length_scaled.tsv",
                                 sep="\t", header=TRUE, check.names=FALSE)
# Other Schwann Cells
rawcountsOtherSchwann <- read.table("../Scaled_Inputs/MajdPrimary_salmon.merged.gene_counts_length_scaled.tsv",
                                    sep="\t", header=TRUE, check.names=FALSE)
  
# Select out the relevant columns of the count maticies
countsIyer <- rawcountsIyer
countsPrimaryDRG <- rawcountsPrimaryDRG[, c("gene_id", "gene_name", "NguyenDRG_34FemA", "NguyenDRG_36Fem")]
countsPrimarySG <- rawcountsPrimarySG
countsPrimarySchwann <- rawcountsPrimarySchwanns[, c("gene_id", "gene_name", "PrimarySchwanns1", "PrimarySchwanns2")]
countsOtherTNC <- rawcountsFattahiTNC
countsOtherSymp <- merge(rawcountsWuSymp, rawcountsLiuSGO, by=c("gene_id", "gene_name"))
sens_tables <- list(rawcountsDeng28Sens, rawcountsDeng56Sens, rawcountsCantorSens, rawcountsMalkaSens)
countsOtherSens <- Reduce(function(x, y) merge(x, y, by=c("gene_id", "gene_name")), sens_tables)
countsOtherSchwann <- rawcountsOtherSchwann[, c("gene_id", "gene_name", "SC_old1", "SC_old2", "SC_young1", "SC_young2")]
  
# combine counts and write to new tsv for further analysis
count_list <- list(
  countsIyer,
  countsPrimaryDRG,
  countsPrimarySG,
  countsPrimarySchwann,
  countsOtherTNC,
  countsOtherSymp,
  countsOtherSens,
  countsOtherSchwann
)

# merge them all by gene_id and gene_name, keeping those columns only once
merged_counts <- Reduce(function(x, y) merge(x, y, by = c("gene_id", "gene_name"), all = TRUE), count_list)
write.table(merged_counts, "Combined_scaled_counts_v3.tsv", sep="\t", quote=FALSE, row.names=FALSE)

# Generate metadata mappings
sample_cols <- colnames(merged_counts)[-(1:2)]
metadata <- data.frame(
  sample = sample_cols,
  row.names = sample_cols,
  stringsAsFactors = FALSE
)

celltype_map <- c("Lippmann_TNC_1003"="tNC", "Lippmann_TNC_1107" = "tNC",
                  "Fattahi_defaultNC_1"="tNC", "Fattahi_defaultNC_2"="tNC",
                  "Fattahi_defaultNC_3"="tNC", "Fattahi_entericNC_1"="tNC",
                  "Fattahi_entericNC_2"="tNC", "Fattahi_entericNC_3"="tNC",
                  "TNC_SC_D64_1003"="Schwanns", "TNC_SC_D64_1015"= "Schwanns",
                  "TNC_SN_D36_0131"="Sensory", "TNC_SN_D36_0913"="Sensory",
                  "TNC_SympN_D36_1003"="Sympathetic", "TNC_SympN_D36_1107"="Sympathetic",
                  "NguyenDRG_34FemA"="Sensory", "NguyenDRG_36Fem"="Sensory",
                  "HabermanSG_merged"="Sympathetic", "PrimarySchwanns1"="Schwanns",
                  "PrimarySchwanns2"="Schwanns", "Wu_SympN1"="Sympathetic",
                  "Wu_SympN2"="Sympathetic", "Wu_SympN3"="Sympathetic",
                  "Wu_SympN4"="Sympathetic", "Liu_SGOrganoid"="Sympathetic",
                  "Deng_D28SensN1"="Sensory", "Deng_D28SensN2"="Sensory", 
                  "Deng_D28SensN3"="Sensory", "Deng_D56_1"="Sensory",
                  "Deng_D56_2"="Sensory", "Deng_D56_3"="Sensory",
                  "Can_SNs_HP1"="Sensory", "Can_SNs_HP2"="Sensory",
                  "Can_SNs_HP3"="Sensory", "MalG_nociceptor_DIV60_1"="Sensory",
                  "MalG_nociceptor_DIV60_2"="Sensory", 
                  "MalG_nociceptor_DIV60_3"="Sensory", 
                  "MalG_nociceptor_DIV60_4"="Sensory", "SC_old1"="Schwanns", 
                  "SC_old2"="Schwanns", "SC_young1"="Schwanns", "SC_young2"="Schwanns")
metadata$cell_type <- celltype_map[metadata$sample]

cellsource_map <- c("Lippmann_TNC_1003"="Iyer", "Lippmann_TNC_1107" = "Iyer",
                    "Fattahi_defaultNC_1"="Other", "Fattahi_defaultNC_2"="Other",
                    "Fattahi_defaultNC_3"="Other", "Fattahi_entericNC_1"="Other",
                    "Fattahi_entericNC_2"="Other", "Fattahi_entericNC_3"="Other",
                    "TNC_SC_D64_1003"="Iyer", "TNC_SC_D64_1015"= "Iyer",
                    "TNC_SN_D36_0131"="Iyer", "TNC_SN_D36_0913"="Iyer",
                    "TNC_SympN_D36_1003"="Iyer", "TNC_SympN_D36_1107"="Iyer",
                    "NguyenDRG_34FemA"="Primary", "NguyenDRG_36Fem"="Primary",
                    "HabermanSG_merged"="Primary", "PrimarySchwanns1"="Primary",
                    "PrimarySchwanns2"="Primary", "Wu_SympN1"="Other",
                    "Wu_SympN2"="Other", "Wu_SympN3"="Other",
                    "Wu_SympN4"="Other", "Liu_SGOrganoid"="Other",
                    "Deng_D28SensN1"="Other", "Deng_D28SensN2"="Other", 
                    "Deng_D28SensN3"="Other", "Deng_D56_1"="Other",
                    "Deng_D56_2"="Other", "Deng_D56_3"="Other",
                    "Can_SNs_HP1"="Other", "Can_SNs_HP2"="Other",
                    "Can_SNs_HP3"="Other", "MalG_nociceptor_DIV60_1"="Other",
                    "MalG_nociceptor_DIV60_2"="Other", 
                    "MalG_nociceptor_DIV60_3"="Other", 
                    "MalG_nociceptor_DIV60_4"="Other", "SC_old1"="Other", 
                    "SC_old2"="Other", "SC_young1"="Other", "SC_young2"="Other")
metadata$cell_source <- cellsource_map[metadata$sample]

cellpub_map <- c("Lippmann_TNC_1003"="This Study", "Lippmann_TNC_1107" = "This Study",
                 "Fattahi_defaultNC_1"="Fattahi et al. (2016)", "Fattahi_defaultNC_2"="Fattahi et al. (2016)",
                 "Fattahi_defaultNC_3"="Fattahi et al. (2016)", "Fattahi_entericNC_1"="Fattahi et al. (2016)",
                 "Fattahi_entericNC_2"="Fattahi et al. (2016)", "Fattahi_entericNC_3"="Fattahi et al. (2016)",
                 "TNC_SC_D64_1003"="This Study", "TNC_SC_D64_1015"= "This Study",
                 "TNC_SN_D36_0131"="This Study", "TNC_SN_D36_0913"="This Study",
                 "TNC_SympN_D36_1003"="This Study", "TNC_SympN_D36_1107"="This Study",
                 "NguyenDRG_34FemA"="Primary Human DRG (Nguyen 2021)", "NguyenDRG_36Fem"="Primary Human DRG (Nguyen 2021)",
                 "HabermanSG_merged"="Primary Human Sympathetic Ganglion (Haberman 2024)", 
                 "PrimarySchwanns1"="Primary Human Schwann Cells (Majd 2023)",
                 "PrimarySchwanns2"="Primary Human Schwann Cells (Majd 2023)", "Wu_SympN1"="Wu et al. (2024)",
                 "Wu_SympN2"="Wu et al. (2024)", "Wu_SympN3"="Wu et al. (2024)",
                 "Wu_SympN4"="Wu et al. (2024)", "Liu_SGOrganoid"="Liu et al. (2026)",
                 "Deng_D28SensN1"="Deng et al. D28 (2023)", "Deng_D28SensN2"="Deng et al. D28 (2023)", 
                 "Deng_D28SensN3"="Deng et al. D28 (2023)", "Deng_D56_1"="Deng et al. D56 (2023)",
                 "Deng_D56_2"="Deng et al. D56 (2023)", "Deng_D56_3"="Deng et al. D56 (2023)",
                 "Can_SNs_HP1"="Cantor et al. (2022)", "Can_SNs_HP2"="Cantor et al. (2022)",
                 "Can_SNs_HP3"="Cantor et al. (2022)", "MalG_nociceptor_DIV60_1"="Malka-Gibor et al. (2026)",
                 "MalG_nociceptor_DIV60_2"="Malka-Gibor et al. (2026)", 
                 "MalG_nociceptor_DIV60_3"="Malka-Gibor et al. (2026)", 
                 "MalG_nociceptor_DIV60_4"="Malka-Gibor et al. (2026)", "SC_old1"="Majd et al. HP (2023)", 
                 "SC_old2"="Majd et al. HP (2023)", "SC_young1"="Majd et al. LP (2023)", "SC_young2"="Majd et al. LP (2023)")
metadata$cell_publication <- cellpub_map[metadata$sample]

# Write metadata to TSV
write.table(metadata, "../sample_metadata_v3.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

  